name: Our CI
on:
  schedule:
    # At minute 0 past every hour.
    - cron: "0 */1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node 22.x
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Fetch RSS Blogs
        run: node ./scripts/rss.parse.js
