name: Fetch rss files
on:
  schedule:
    # At minute 0 past every hour.
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Fetch RSS Blogs
        run: node ./scripts/rss.parse.js

      - name: Commit Result
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
